- import_playbook: setup_stratum-0.yaml
- import_playbook: setup_stratum-1.yaml
- import_playbook: setup_proxies.yaml

- hosts: all
  gather_facts: true

- hosts: stratum_0
  gather_facts: false
  become: true
  vars_files:
    - vars.yaml
  
  tasks:
    - name: Stop autofs service
      service:
        name: autofs.service
        state: stopped

    - include_tasks: tasks/add_stratum-0_repository.yaml
      loop: "{{ cvmfs_server.repositories }}"


- hosts: stratum_1s
  gather_facts: false
  become: true
  vars_files:
    - vars.yaml
  
  tasks:
    - include_tasks: tasks/add_stratum-1_repository.yaml
      loop: "{{ cvmfs_server.repositories }}"


- hosts: proxies
  gather_facts: false
  become: true
  vars_files:
    - vars.yaml

  tasks:
    - include_tasks: tasks/add_proxy.yaml
      loop: "{{ cvmfs_server.repositories }}"


- hosts: clients
  gather_facts: false
  become: true  
  vars_files:
    - vars.yaml

  tasks:
    - include_tasks: tasks/add_client.yaml
      loop: "{{ cvmfs_server.repositories }}"

    - name: Create default.local
      copy:
        dest: "/etc/cvmfs/default.local"
        content: |
          CVMFS_REPOSITORIES="{{ cvmfs_server.repositories|join(',') }}"
          CVMFS_HTTP_PROXY="http://{{ groups['proxies'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])|join(':3128;http://') }}:3128"
          

