cvmfs:
  hosts:
    ltpord01:
      ansible_host: t3ltpord01.psi.ch
      ansible_user: mfatouro
    ltpord02:
      ansible_host: t3ltpord02.psi.ch
      ansible_user: mfatouro
    ltpord03:
      ansible_host: t3ltpord03.psi.ch
      ansible_user: mfatouro
    ltpord04:
      ansible_host: t3ltpord04.psi.ch
      ansible_user: mfatouro
    pc16571:
      ansible_host: pc16571.psi.ch
      ansible_user: psihep
    pc12011:
      ansible_host: pc12011.psi.ch
      ansible_user: psihep

  vars:
    repositories:
      - testing.psi.ch


# There should only be one stratum_0 at a time
stratum_0:
  hosts:
    ltpord01:

stratum_1s:
  hosts:
    ltpord02:

proxies:
  hosts:
    ltpord03:
    pc16571:

  vars:
    proxy:
      cache_size: 5000  # MB

clients:
  hosts:
    # ltpord04:
    # pc16571:
    pc12011:
