- hosts: stratum_1s
  become: true
  vars_files:
    - vars.yaml
  
  tasks:
    - import_tasks: tasks/install_cvmfs-server.yaml

    - name: Install squid proxy
      package:
        name: squid

    - name: Modify Apache config
      lineinfile:
        path: "/etc/httpd/conf/httpd.conf"
        regexp: "^Listen 80"
        line: "Listen 127.0.0.1:8080"

    - name: Copy over squid config
      copy:
        src: "templates/reverse_proxy.conf"
        dest: "/etc/squid/squid.conf"

    - name: Start Apache webserver
      service:
        name: httpd.service
        state: started
        enabled: true

    - name: Start squid proxy
      service:
        name: squid.service
        state: started
        enabled: true



