- name: Install Autofs
  package:
    name: autofs

- name: start Autofs
  service:
    name: autofs.service
    state: started
    enabled: yes

- include_tasks: add_client.yml
  loop: "{{ repositories }}"

- name: Create default.local
  copy:
    dest: "/etc/cvmfs/default.local"
    content: |
      CVMFS_REPOSITORIES="{{ repositories|join(',') }}"
      CVMFS_HTTP_PROXY="http://{{ groups['proxies'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])|join(':3128;http://') }}:3128"

- name: setup client
  command: cvmfs_config setup
