- name: Take the string "<org.tld>" from "<repo.org.tld>"
  set_fact:
    domain_name: "{{ (item|split('.'))[1:]|join('.') }}"


- name: Add log config
  blockinfile:
    path: "/etc/cvmfs/config.d/{{ item }}.conf"
    block: |
      /var/log/cvmfs/*.log {
        weekly
        missingok
        notifempty
      }
    create: true

- name: Ensure key directory exists
  file:
    path: "/etc/cvmfs/keys/{{ domain_name }}/"
    state: directory

- name: Upload stratum 0 public keys for each repository
  copy:
    src: "/tmp/{{ item }}.pub"
    dest: "/etc/cvmfs/keys/{{ domain_name }}/{{ item }}.pub"



- name: Get list of cvmfs repositories
  shell: cvmfs_server list
  register: cvmfs_server_list


- name: Add replica repository from Stratum 0
  shell:
    cmd: |
      cvmfs_server add-replica http://{{ hostvars[groups['stratum_0'][0]]['ansible_default_ipv4']['address'] }}/cvmfs/{{ item }} /etc/cvmfs/keys/{{ domain_name }}/ <<< "
      "
    creates: "/var/spool/cvmfs/{{ item }}"
  when:
    "not cvmfs_server_list.stdout | regex_search('^item  ', multiline=True)"


- name: Update Stratum 1 repositories
  command:
    cmd: "cvmfs_server snapshot {{ item }}"

- name: Upload log rotation rules
  blockinfile:
    path: /etc/logrotate.d/cvmfs
    block: |
      /var/log/cvmfs/*.log {
        weekly
        missingok
        notifempty
      }
    create: true

- name: Add cron job to update repository
  lineinfile:
    path: /etc/cron.d/cvmfs_stratum-1_snapshot
    line: '*/5 * * * * root output=$(/usr/bin/cvmfs_server snapshot -a -i 2>&1) || echo "$output"'
    create: true


