- name: Install squid
  package:
    name: squid

- name: Upload squid config
  template:
    src: "forward_proxy.j2"
    dest: "/etc/squid/squid.conf"

- name: Start squid proxy
  service:
    name: squid.service
    state: started
    enabled: true



