- name: Install squid
  package:
    name: squid


- name: Get stratum 1 if defined, else stratum 0.
  set_fact:
    group: "{{ groups['stratum_1s'] | default( groups['stratum_0'], true)}}"

- name: Print group
  debug:
    var: group

- name: Upload squid config
  template:
    src: "forward_proxy.j2"
    dest: "/etc/squid/squid.conf"

- name: Start squid proxy
  service:
    name: squid.service
    state: started
    enabled: true



