- hosts:
    - proxies
    - stratum_1s
  gather_facts: true

- name: Setup CVMFS Clients
  hosts: clients
  gather_facts: true
  become: true
  collections:
    - cvmfs.setup
  roles:
    - cvmfs.setup.common
    - cvmfs.setup.clients
