- hosts:
    - stratum_0
    - stratum_1s
  gather_facts: true

- name: Setup proxies
  hosts: proxies
  gather_facts: false
  become: true
  collections:
    - cvmfs.setup
  roles:
    - cvmfs.setup.common
    - cvmfs.setup.proxies
