- hosts: stratum_0
  gather_facts: true

- name: Setup CVMFS Stratum 1
  hosts: stratum_1s
  gather_facts: false
  become: true
  collections:
    - cvmfs.setup
  roles:
    - cvmfs.setup.common
    - cvmfs.setup.stratum_1
