name: Test ansible

on:
  push:
    branches: [ $default-branch, action ]
  pull_request:
    branches: [ $default-branch, action]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update
      - run: apt-get install -y pip podman ansible
      - run: pip install molecule molecule-podman

      - name: build and install this collection
        run: ansible-galaxy collection install .

      - name: run ansible molecule tests
        working-directory: ./extensions
        run: molecule test
